version: '3.9'

services:
  calico.postgres:
    container_name: calico_postgres
    networks:
      - calico_net
    image: postgres:14.1-alpine3.14
    volumes:
      - ./_cache/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 'pass'
      POSTGRES_DB: 'calico'
      PGDATA: '/var/lib/postgresql/data'
    ports:
      - 5432:5432

  calico.server:
    container_name: calico_server
    networks:
      - calico_net
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules/

  calico.synchronizer:
    container_name: calico_synchronizer
    networks:
      - calico_net
    build:
      context: .
      dockerfile: ./docker/synchronizer/Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules/

  calico.mobile:
    container_name: calico_mobile
    networks:
      - calico_net
    build:
      context: .
      dockerfile: ./docker/mobile/Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules/
    ports:
      - 19000:19000
      - 19006:19006

networks:
  calico_net:
    name: calico_net
